apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.configService.name }}
spec:
  selector:
    app: {{ .Values.configService.name }}
  ports:
    - port: {{ .Values.configService.port }}
      targetPort: {{ .Values.configService.port }}
  type: ClusterIP
