apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zipkin.name }}
spec:
  selector:
    app: {{ .Values.zipkin.name }}
  type: NodePort
  ports:
    - port: {{ .Values.zipkin.port }}
      targetPort: {{ .Values.zipkin.port }}
